apiVersion: apps/v1
kind: Deployment
metadata:
  name: appadd-deployment
  labels:
    app: appadd
<<<<<<< HEAD
    type: local  
=======
>>>>>>> 272868c22751a73c5ea6de0d01fb934d621ca0d1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appadd
  template:
    metadata:
      labels:
        app: appadd
    spec:
      containers:
      - name: appadd
<<<<<<< HEAD
        image: hamzax01/h_php:6.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom: 
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
          - name: URL
            valueFrom: 
              configMapKeyRef:
                name: postgres-configmap
                key: URL
=======
        image: younessberianebadi/addapp:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
>>>>>>> 272868c22751a73c5ea6de0d01fb934d621ca0d1
